FROM gcc:14.4.0-trixie

RUN apt-get update && apt-get install -y \
    clang-tidy \
    clang \
    build-essential \
    cmake \
    ninja-build \
    gdb \
    git \
    curl \
    zip \
    unzip \
    tar \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app